//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInformation
    {
        public int carID { get; set; }
        public string carName { get; set; }
        public Nullable<int> ageRequired { get; set; }
        public Nullable<bool> airBag { get; set; }
        public Nullable<int> baggageVolume { get; set; }
        public Nullable<int> numberOfSeats { get; set; }
        public Nullable<decimal> dailyRentalPrice { get; set; }
        public Nullable<decimal> hourlyRentalPrice { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
