//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyInformation()
        {
            this.RentalInformation = new HashSet<RentalInformation>();
        }
    
        public int companyID { get; set; }
        public string companyName { get; set; }
        public Nullable<int> addressID { get; set; }
        public string numberOfCar { get; set; }
        public string companyScore { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalInformation> RentalInformation { get; set; }
    }
}
