//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalInformation
    {
        public int rentalID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> rentalDate { get; set; }
        public Nullable<decimal> rentalPrice { get; set; }
        public Nullable<int> carID { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> rentalDay { get; set; }
    
        public virtual CompanyInformation CompanyInformation { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
