//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.WinFormUI.CarRentalUserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        private System.Nullable<int> roleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.UserInformation UserInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> roleID {
            get {
                return this.roleIDField;
            }
            set {
                if ((this.roleIDField.Equals(value) != true)) {
                    this.roleIDField = value;
                    this.RaisePropertyChanged("roleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CarRental.WinFormUI.CarRentalUserService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRental.WinFormUI.CarRentalUserService.UserInformation UserInformation {
            get {
                return this.UserInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInformationField, value) != true)) {
                    this.UserInformationField = value;
                    this.RaisePropertyChanged("UserInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int roleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.User[] UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int roleID {
            get {
                return this.roleIDField;
            }
            set {
                if ((this.roleIDField.Equals(value) != true)) {
                    this.roleIDField = value;
                    this.RaisePropertyChanged("roleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string roleName {
            get {
                return this.roleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.roleNameField, value) != true)) {
                    this.roleNameField = value;
                    this.RaisePropertyChanged("roleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CarRental.WinFormUI.CarRentalUserService.User[] User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInformation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        private System.Nullable<int> phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.RentalInformation[] RentalInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((this.phoneNumberField.Equals(value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CarRental.WinFormUI.CarRentalUserService.RentalInformation[] RentalInformation {
            get {
                return this.RentalInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalInformationField, value) != true)) {
                    this.RentalInformationField = value;
                    this.RaisePropertyChanged("RentalInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CarRental.WinFormUI.CarRentalUserService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalInformation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentalInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int rentalIDField;
        
        private System.Nullable<int> userIDField;
        
        private System.Nullable<System.DateTime> rentalDateField;
        
        private System.Nullable<decimal> rentalPriceField;
        
        private System.Nullable<int> carIDField;
        
        private System.Nullable<int> companyIDField;
        
        private System.Nullable<int> rentalDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.CompanyInformation CompanyInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.UserInformation UserInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int rentalID {
            get {
                return this.rentalIDField;
            }
            set {
                if ((this.rentalIDField.Equals(value) != true)) {
                    this.rentalIDField = value;
                    this.RaisePropertyChanged("rentalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> rentalDate {
            get {
                return this.rentalDateField;
            }
            set {
                if ((this.rentalDateField.Equals(value) != true)) {
                    this.rentalDateField = value;
                    this.RaisePropertyChanged("rentalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> rentalPrice {
            get {
                return this.rentalPriceField;
            }
            set {
                if ((this.rentalPriceField.Equals(value) != true)) {
                    this.rentalPriceField = value;
                    this.RaisePropertyChanged("rentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> carID {
            get {
                return this.carIDField;
            }
            set {
                if ((this.carIDField.Equals(value) != true)) {
                    this.carIDField = value;
                    this.RaisePropertyChanged("carID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> companyID {
            get {
                return this.companyIDField;
            }
            set {
                if ((this.companyIDField.Equals(value) != true)) {
                    this.companyIDField = value;
                    this.RaisePropertyChanged("companyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> rentalDay {
            get {
                return this.rentalDayField;
            }
            set {
                if ((this.rentalDayField.Equals(value) != true)) {
                    this.rentalDayField = value;
                    this.RaisePropertyChanged("rentalDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CarRental.WinFormUI.CarRentalUserService.CompanyInformation CompanyInformation {
            get {
                return this.CompanyInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyInformationField, value) != true)) {
                    this.CompanyInformationField = value;
                    this.RaisePropertyChanged("CompanyInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRental.WinFormUI.CarRentalUserService.UserInformation UserInformation {
            get {
                return this.UserInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInformationField, value) != true)) {
                    this.UserInformationField = value;
                    this.RaisePropertyChanged("UserInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyInformation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CompanyInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int companyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        private System.Nullable<int> addressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numberOfCarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.RentalInformation[] RentalInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int companyID {
            get {
                return this.companyIDField;
            }
            set {
                if ((this.companyIDField.Equals(value) != true)) {
                    this.companyIDField = value;
                    this.RaisePropertyChanged("companyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> addressID {
            get {
                return this.addressIDField;
            }
            set {
                if ((this.addressIDField.Equals(value) != true)) {
                    this.addressIDField = value;
                    this.RaisePropertyChanged("addressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string numberOfCar {
            get {
                return this.numberOfCarField;
            }
            set {
                if ((object.ReferenceEquals(this.numberOfCarField, value) != true)) {
                    this.numberOfCarField = value;
                    this.RaisePropertyChanged("numberOfCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string companyScore {
            get {
                return this.companyScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.companyScoreField, value) != true)) {
                    this.companyScoreField = value;
                    this.RaisePropertyChanged("companyScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CarRental.WinFormUI.CarRentalUserService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRental.WinFormUI.CarRentalUserService.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CarRental.WinFormUI.CarRentalUserService.RentalInformation[] RentalInformation {
            get {
                return this.RentalInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalInformationField, value) != true)) {
                    this.RentalInformationField = value;
                    this.RaisePropertyChanged("RentalInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int addressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.CompanyInformation[] CompanyInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int addressID {
            get {
                return this.addressIDField;
            }
            set {
                if ((this.addressIDField.Equals(value) != true)) {
                    this.addressIDField = value;
                    this.RaisePropertyChanged("addressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                if ((object.ReferenceEquals(this.provinceField, value) != true)) {
                    this.provinceField = value;
                    this.RaisePropertyChanged("province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CarRental.WinFormUI.CarRentalUserService.CompanyInformation[] CompanyInformation {
            get {
                return this.CompanyInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyInformationField, value) != true)) {
                    this.CompanyInformationField = value;
                    this.RaisePropertyChanged("CompanyInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int companyIDField;
        
        private System.Nullable<int> companyInfoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Car[] CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.CompanyInformation CompanyInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int companyID {
            get {
                return this.companyIDField;
            }
            set {
                if ((this.companyIDField.Equals(value) != true)) {
                    this.companyIDField = value;
                    this.RaisePropertyChanged("companyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> companyInfoID {
            get {
                return this.companyInfoIDField;
            }
            set {
                if ((this.companyInfoIDField.Equals(value) != true)) {
                    this.companyInfoIDField = value;
                    this.RaisePropertyChanged("companyInfoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CarRental.WinFormUI.CarRentalUserService.Car[] Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CarRental.WinFormUI.CarRentalUserService.CompanyInformation CompanyInformation {
            get {
                return this.CompanyInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyInformationField, value) != true)) {
                    this.CompanyInformationField = value;
                    this.RaisePropertyChanged("CompanyInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int carIDField;
        
        private System.Nullable<int> markIDField;
        
        private System.Nullable<int> modelIDField;
        
        private System.Nullable<int> companyIDField;
        
        private System.Nullable<bool> rentalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.CarInformation CarInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Mark MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Model ModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int carID {
            get {
                return this.carIDField;
            }
            set {
                if ((this.carIDField.Equals(value) != true)) {
                    this.carIDField = value;
                    this.RaisePropertyChanged("carID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> markID {
            get {
                return this.markIDField;
            }
            set {
                if ((this.markIDField.Equals(value) != true)) {
                    this.markIDField = value;
                    this.RaisePropertyChanged("markID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> modelID {
            get {
                return this.modelIDField;
            }
            set {
                if ((this.modelIDField.Equals(value) != true)) {
                    this.modelIDField = value;
                    this.RaisePropertyChanged("modelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> companyID {
            get {
                return this.companyIDField;
            }
            set {
                if ((this.companyIDField.Equals(value) != true)) {
                    this.companyIDField = value;
                    this.RaisePropertyChanged("companyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<bool> rentalStatus {
            get {
                return this.rentalStatusField;
            }
            set {
                if ((this.rentalStatusField.Equals(value) != true)) {
                    this.rentalStatusField = value;
                    this.RaisePropertyChanged("rentalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CarRental.WinFormUI.CarRentalUserService.CarInformation CarInformation {
            get {
                return this.CarInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CarInformationField, value) != true)) {
                    this.CarInformationField = value;
                    this.RaisePropertyChanged("CarInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarRental.WinFormUI.CarRentalUserService.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CarRental.WinFormUI.CarRentalUserService.Mark Mark {
            get {
                return this.MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkField, value) != true)) {
                    this.MarkField = value;
                    this.RaisePropertyChanged("Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRental.WinFormUI.CarRentalUserService.Model Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarInformation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CarInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int carIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carNameField;
        
        private System.Nullable<int> ageRequiredField;
        
        private System.Nullable<bool> airBagField;
        
        private System.Nullable<int> baggageVolumeField;
        
        private System.Nullable<int> numberOfSeatsField;
        
        private System.Nullable<decimal> dailyRentalPriceField;
        
        private System.Nullable<decimal> hourlyRentalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Car CarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int carID {
            get {
                return this.carIDField;
            }
            set {
                if ((this.carIDField.Equals(value) != true)) {
                    this.carIDField = value;
                    this.RaisePropertyChanged("carID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carName {
            get {
                return this.carNameField;
            }
            set {
                if ((object.ReferenceEquals(this.carNameField, value) != true)) {
                    this.carNameField = value;
                    this.RaisePropertyChanged("carName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> ageRequired {
            get {
                return this.ageRequiredField;
            }
            set {
                if ((this.ageRequiredField.Equals(value) != true)) {
                    this.ageRequiredField = value;
                    this.RaisePropertyChanged("ageRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<bool> airBag {
            get {
                return this.airBagField;
            }
            set {
                if ((this.airBagField.Equals(value) != true)) {
                    this.airBagField = value;
                    this.RaisePropertyChanged("airBag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> baggageVolume {
            get {
                return this.baggageVolumeField;
            }
            set {
                if ((this.baggageVolumeField.Equals(value) != true)) {
                    this.baggageVolumeField = value;
                    this.RaisePropertyChanged("baggageVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> numberOfSeats {
            get {
                return this.numberOfSeatsField;
            }
            set {
                if ((this.numberOfSeatsField.Equals(value) != true)) {
                    this.numberOfSeatsField = value;
                    this.RaisePropertyChanged("numberOfSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> dailyRentalPrice {
            get {
                return this.dailyRentalPriceField;
            }
            set {
                if ((this.dailyRentalPriceField.Equals(value) != true)) {
                    this.dailyRentalPriceField = value;
                    this.RaisePropertyChanged("dailyRentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> hourlyRentalPrice {
            get {
                return this.hourlyRentalPriceField;
            }
            set {
                if ((this.hourlyRentalPriceField.Equals(value) != true)) {
                    this.hourlyRentalPriceField = value;
                    this.RaisePropertyChanged("hourlyRentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarRental.WinFormUI.CarRentalUserService.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mark", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Mark : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int markIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string markNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Car[] CarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int markID {
            get {
                return this.markIDField;
            }
            set {
                if ((this.markIDField.Equals(value) != true)) {
                    this.markIDField = value;
                    this.RaisePropertyChanged("markID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string markName {
            get {
                return this.markNameField;
            }
            set {
                if ((object.ReferenceEquals(this.markNameField, value) != true)) {
                    this.markNameField = value;
                    this.RaisePropertyChanged("markName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CarRental.WinFormUI.CarRentalUserService.Car[] Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Model : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int modelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRental.WinFormUI.CarRentalUserService.Car[] CarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int modelID {
            get {
                return this.modelIDField;
            }
            set {
                if ((this.modelIDField.Equals(value) != true)) {
                    this.modelIDField = value;
                    this.RaisePropertyChanged("modelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string modelName {
            get {
                return this.modelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.modelNameField, value) != true)) {
                    this.modelNameField = value;
                    this.RaisePropertyChanged("modelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CarRental.WinFormUI.CarRentalUserService.Car[] Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarRentalUserService.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        CarRental.WinFormUI.CarRentalUserService.AddResponse Add(CarRental.WinFormUI.CarRentalUserService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.AddResponse> AddAsync(CarRental.WinFormUI.CarRentalUserService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        CarRental.WinFormUI.CarRentalUserService.GetResponse Get(CarRental.WinFormUI.CarRentalUserService.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.GetResponse> GetAsync(CarRental.WinFormUI.CarRentalUserService.GetRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        CarRental.WinFormUI.CarRentalUserService.GetAllResponse GetAll(CarRental.WinFormUI.CarRentalUserService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.GetAllResponse> GetAllAsync(CarRental.WinFormUI.CarRentalUserService.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        CarRental.WinFormUI.CarRentalUserService.UpdateResponse Update(CarRental.WinFormUI.CarRentalUserService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.UpdateResponse> UpdateAsync(CarRental.WinFormUI.CarRentalUserService.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(CarRental.WinFormUI.CarRentalUserService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.User entity;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(CarRental.WinFormUI.CarRentalUserService.User entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(CarRental.WinFormUI.CarRentalUserService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(CarRental.WinFormUI.CarRentalUserService.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(CarRental.WinFormUI.CarRentalUserService.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.User GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(CarRental.WinFormUI.CarRentalUserService.User GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(CarRental.WinFormUI.CarRentalUserService.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(CarRental.WinFormUI.CarRentalUserService.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.User[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(CarRental.WinFormUI.CarRentalUserService.User[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(CarRental.WinFormUI.CarRentalUserService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.User entity;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(CarRental.WinFormUI.CarRentalUserService.User entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarRental.WinFormUI.CarRentalUserService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(CarRental.WinFormUI.CarRentalUserService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : CarRental.WinFormUI.CarRentalUserService.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<CarRental.WinFormUI.CarRentalUserService.UserServiceSoap>, CarRental.WinFormUI.CarRentalUserService.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRental.WinFormUI.CarRentalUserService.AddResponse CarRental.WinFormUI.CarRentalUserService.UserServiceSoap.Add(CarRental.WinFormUI.CarRentalUserService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(CarRental.WinFormUI.CarRentalUserService.User entity) {
            CarRental.WinFormUI.CarRentalUserService.AddRequest inValue = new CarRental.WinFormUI.CarRentalUserService.AddRequest();
            inValue.Body = new CarRental.WinFormUI.CarRentalUserService.AddRequestBody();
            inValue.Body.entity = entity;
            CarRental.WinFormUI.CarRentalUserService.AddResponse retVal = ((CarRental.WinFormUI.CarRentalUserService.UserServiceSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.AddResponse> CarRental.WinFormUI.CarRentalUserService.UserServiceSoap.AddAsync(CarRental.WinFormUI.CarRentalUserService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.AddResponse> AddAsync(CarRental.WinFormUI.CarRentalUserService.User entity) {
            CarRental.WinFormUI.CarRentalUserService.AddRequest inValue = new CarRental.WinFormUI.CarRentalUserService.AddRequest();
            inValue.Body = new CarRental.WinFormUI.CarRentalUserService.AddRequestBody();
            inValue.Body.entity = entity;
            return ((CarRental.WinFormUI.CarRentalUserService.UserServiceSoap)(this)).AddAsync(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRental.WinFormUI.CarRentalUserService.GetResponse CarRental.WinFormUI.CarRentalUserService.UserServiceSoap.Get(CarRental.WinFormUI.CarRentalUserService.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public CarRental.WinFormUI.CarRentalUserService.User Get(int id) {
            CarRental.WinFormUI.CarRentalUserService.GetRequest inValue = new CarRental.WinFormUI.CarRentalUserService.GetRequest();
            inValue.Body = new CarRental.WinFormUI.CarRentalUserService.GetRequestBody();
            inValue.Body.id = id;
            CarRental.WinFormUI.CarRentalUserService.GetResponse retVal = ((CarRental.WinFormUI.CarRentalUserService.UserServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.GetResponse> CarRental.WinFormUI.CarRentalUserService.UserServiceSoap.GetAsync(CarRental.WinFormUI.CarRentalUserService.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.GetResponse> GetAsync(int id) {
            CarRental.WinFormUI.CarRentalUserService.GetRequest inValue = new CarRental.WinFormUI.CarRentalUserService.GetRequest();
            inValue.Body = new CarRental.WinFormUI.CarRentalUserService.GetRequestBody();
            inValue.Body.id = id;
            return ((CarRental.WinFormUI.CarRentalUserService.UserServiceSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRental.WinFormUI.CarRentalUserService.GetAllResponse CarRental.WinFormUI.CarRentalUserService.UserServiceSoap.GetAll(CarRental.WinFormUI.CarRentalUserService.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public CarRental.WinFormUI.CarRentalUserService.User[] GetAll() {
            CarRental.WinFormUI.CarRentalUserService.GetAllRequest inValue = new CarRental.WinFormUI.CarRentalUserService.GetAllRequest();
            inValue.Body = new CarRental.WinFormUI.CarRentalUserService.GetAllRequestBody();
            CarRental.WinFormUI.CarRentalUserService.GetAllResponse retVal = ((CarRental.WinFormUI.CarRentalUserService.UserServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.GetAllResponse> CarRental.WinFormUI.CarRentalUserService.UserServiceSoap.GetAllAsync(CarRental.WinFormUI.CarRentalUserService.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.GetAllResponse> GetAllAsync() {
            CarRental.WinFormUI.CarRentalUserService.GetAllRequest inValue = new CarRental.WinFormUI.CarRentalUserService.GetAllRequest();
            inValue.Body = new CarRental.WinFormUI.CarRentalUserService.GetAllRequestBody();
            return ((CarRental.WinFormUI.CarRentalUserService.UserServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRental.WinFormUI.CarRentalUserService.UpdateResponse CarRental.WinFormUI.CarRentalUserService.UserServiceSoap.Update(CarRental.WinFormUI.CarRentalUserService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(CarRental.WinFormUI.CarRentalUserService.User entity) {
            CarRental.WinFormUI.CarRentalUserService.UpdateRequest inValue = new CarRental.WinFormUI.CarRentalUserService.UpdateRequest();
            inValue.Body = new CarRental.WinFormUI.CarRentalUserService.UpdateRequestBody();
            inValue.Body.entity = entity;
            CarRental.WinFormUI.CarRentalUserService.UpdateResponse retVal = ((CarRental.WinFormUI.CarRentalUserService.UserServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.UpdateResponse> CarRental.WinFormUI.CarRentalUserService.UserServiceSoap.UpdateAsync(CarRental.WinFormUI.CarRentalUserService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRental.WinFormUI.CarRentalUserService.UpdateResponse> UpdateAsync(CarRental.WinFormUI.CarRentalUserService.User entity) {
            CarRental.WinFormUI.CarRentalUserService.UpdateRequest inValue = new CarRental.WinFormUI.CarRentalUserService.UpdateRequest();
            inValue.Body = new CarRental.WinFormUI.CarRentalUserService.UpdateRequestBody();
            inValue.Body.entity = entity;
            return ((CarRental.WinFormUI.CarRentalUserService.UserServiceSoap)(this)).UpdateAsync(inValue);
        }
    }
}
